### ISSUE TITLE
Please clarify that this maps out connections between nodes, not UNLs

### ISSUE THREAD

**Issue by MarkusTeufelberger** [SourenP/rippled-network-crawler#4]
Apparently this fact even confuses your own employees:
https://twitter.com/stevenzeiler/status/611690465679642624

The "consensus network" is the graph of all UNLs between validator public keys. This data is private to each validator and currently can NOT be mapped/crawled.

What this crawler shows are peer connections between servers who (for the most part) don't even participate in Consensus or at least don't have any say in influencing the outcome of a transaction on mainnet.

**Comment by sourencho** [comment]
I'll make sure to make it clear in the README

**Comment by MarkusTeufelberger** [comment]
Thanks. :)

**Comment by vinniefalco** [comment]
There's no way to map out the UNL trust network, nor is that desirable since revealing your UNL is a security risk.

**Comment by MarkusTeufelberger** [comment]
I know, hopefully @stevenzeiler knows too by now. :stuck_out_tongue_winking_eye:
