### ISSUE TITLE
When analyzing a crawl, uncrawlable rippleds should also be considered

### ISSUE THREAD

**Issue by sourencho** [SourenP/rippled-network-crawler#5]
Currently, in my visualization I only include crawlable rippleds - meaning those which have an ip address - but there are many rippleds that don't show their IP addresses which have a public key and peers associated with them. 
Shouldn't forget to include these in analysis and graphs.

**Comment by sourencho** [comment]
The difference is huge: 91 crawlable nodes, 150 nodes with unique pubkeys in total (if i'm not mistaken)

**Comment by vinniefalco** [comment]
Ah, yes those are important! pubkey is the "primary key" - the size of the visible network (or "horizon") is the number of unique public keys reachable on a crawl

**Comment by sourencho** [comment]
Fixed in new_structure pull request #12
