### ISSUE TITLE
Need a way to verify that crawls are correct

### ISSUE THREAD

**Issue by sourencho** [SourenP/rippled-network-crawler#6]
There might be logical bugs that might be producing incorrect data.
Since I have no way of verifying whether or not a crawl is correct based on the graph/analysis (since no one knows how many rippleds there should be), at some point I (and maybe one other person in addition) should go over all the base code again and check it.

**Comment by tdfischer** [comment]
I imagine we can extract the list of peers on all the mainnet client handlers through the peers RPC command (which needs ran locally on the server) to have a second set of data, then compare it to a crawl which doesn't have access to that.

This also has implications that the /crawl API in rippled is correct, which I believe it is. Still something to keep in mind as potential source of bugs.

**Comment by MarkusTeufelberger** [comment]
It is possible to operate a rippled (so you get listed in other rippled's /crawl) and hand out arbitrary data instead of actual useful data when queried at the /crawl address maliciously (e.g. to confuse your tool or to cause you to crawl a certain website/IP).

**Comment by vinniefalco** [comment]
Sure. But that attack is short lived, and its easily detectable (penalize an address each time it fails to provide useful information). There's no incentive to mount such an attack since the gains are nonexistent.

**Comment by stevenzeiler** [comment]
Certainly.

**Comment by intelliot** [comment]
I'm closing this issue because it's over 5 years old and this repo has moved. But if anyone cares about this issue, feel free to open a new one at https://github.com/xpring-eng/rippled-network-crawler/issues and write up some specifics on the work that you think should be done.

**Comment by sourencho** [comment]
😭

**Comment by wilsonianb** [comment]
:wave::smiley:
